export const stack = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vite",
  "Tailwind CSS",
  "React Router",
  "Shadcn UI",
  "Zustand",
  "React Query",
  "Express.js",
  "MongoDB",
  "Jest",
  "ChatGPT",
  "Git",
  "Bible",
  "Ministry",
  "Church",
  "Jesus Christ",
  "Fellowship",
  "Premier League",
  "Arsenal Football Club",
  "Real Estate",
  "Logistics",
  "Ecommerce",
  "Venture Capital",
  "Entreprenuership",
  "Gym",
  "Basketball",
  "Geo-politics",
  "Uganda 🇺🇬",
  "USA",
  "Technology",
  "The Gospel",
  "Industry Design",
  "UI and UX Design",
];
